### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by inelukipg** [tobias-forkel/Magento2_CustomShipping#1]
Hi,
Looks like a great extension!
It would be a great to schedule the shipping method. (Start/end)

**Comment by tobias-forkel** [comment]
Hi @inelukipg 

Your feedback is highly appreciated! I'll provide a schedule feature with the next release. Should be available in a couple of days.

Cheers

**Comment by tobias-forkel** [comment]
Hi @inelukipg 

Version 1.1.0 just released which comes with a datepicker and weekday selector.

Cheers

**Comment by inelukipg** [comment]
Hi @tobias-forkel 
WOW, great! 
I will try it out!

I just thought of one more thing, but I don't know if that's possible. 
Some kind of setting that could hide one or several other shipping methods if this method is active. (multiple select)

If you promote Free shipping, maybe you don't want the customers to be able to choose some other shipping methods.

**Comment by tobias-forkel** [comment]
@inelukipg 

Yeah sounds interesting. I probably add this feature in the next release.

Cheers

**Comment by tobias-forkel** [comment]
@inelukipg 

`Hide Other Shipping Methods` is available in 1.2.0

Cheers
