### ISSUE TITLE
Get error in Custom 1-step Checkout

### ISSUE THREAD

**Issue by inelukipg** [tobias-forkel/Magento2_CustomShipping#3]
Hi,

I tried this extension with our one step checkout Klarna (https://nordicwebteam.se/magento-2-extensions/klarna-checkout-magento-2.html) 
This is an extension that a lot of stores uses in the nordic countries.
It's a free extension, and you can use it with test credentials.

In exception.log file I get:
 [2017-11-28 08:28:32] main.ERROR: Magento\Framework\Exception\LocalizedException: Quote was updated, please review it (check shipping amount, products) in /home/smarthem/www/magento2/app/code/NWT/KCO/Model/Checkout.php:582

**Comment by tobias-forkel** [comment]
Hi @inelukipg 

What is around app/code/NWT/KCO/Model/Checkout.php line 582 ? Can you please provide more information about the model.

Cheers,
Tobias

**Comment by inelukipg** [comment]
Hi,

```
  $qSign = $this->getQuoteSignature($quote);
        $kSign = $klarnaData['merchant_reference']['signature'];

        if($qSign != $kSign) {
           throw new LocalizedException(__("Quote was updated, please review it (check shipping amount, products)"));
        }
```



I attached the Checkout.php file.

[Checkout.zip](https://github.com/tobias-forkel/Magento2_CustomShipping/files/1509836/Checkout.zip)

**Comment by tobias-forkel** [comment]
Hi @inelukipg 

The method **getQuoteSignature** of the extension https://nordicwebteam.se/magento-2-extensions/klarna-checkout-magento-2.html is checking if the quote was manipulated at some point.

I have to manipulate the quote in https://github.com/tobias-forkel/Magento2_CustomShipping/blob/master/Model/Carrier/Custom.php via collectRates otherwise I can't implement a custom shipping method.

So far as I know, this is the only way. Just google for " magento2 collectRates setPrice ". So you may have to get in touch with the guys from nordicwebteam.se to get more information about **getQuoteSignature**. You can also simply try to fix it by your own by removing the exception.

```
throw new LocalizedException(__("Quote was updated, please review it (check shipping amount, products)"));
```

Cheers,
Tobias

**Comment by inelukipg** [comment]
Hi @tobias-forkel 
Thanks!
Thats what I thought. I'll contact them and see if they can explain why they need to check if the quote was manipulated.
But first I'll try to remove that exeption.

**Comment by inelukipg** [comment]
Hi,
Just for info.
If i comment that exeption out I get core error, No shipping method:
main.ERROR: Magento\Framework\Exception\LocalizedException: Please specify a shipping method. in /www/magento2/vendor/magento/module-quote/Model/QuoteValidator.php:55

**Comment by inelukipg** [comment]
I'm not sure, but can it have something to do with this?
(I'm using Magento 2.1.8)

Custom Shipping name could be to long?
`forkel_customshipping_forkel_customshipping`

https://github.com/magento/magento2/issues/5021

**Comment by tobias-forkel** [comment]
Hi @inelukipg 

Yeah looks like the shipping method code is too long. I'll test it in 2.1.8 again and change the length if necessary.

I'll keep you posted.

**Comment by tobias-forkel** [comment]
Hi @inelukipg 

I wasn't able to reproduce it on a clean 2.1.8 setup. However, I will test it without an underscore, as suggested in https://github.com/magento/magento2/issues/5021

I will keep you posted.

**Comment by inelukipg** [comment]
Hi,
Ok thanks!

**Comment by inelukipg** [comment]
Hi, 
I'm just curious if it was the underscores that caused the error?

**Comment by tobias-forkel** [comment]
Hi @inelukipg 

Please use the latest version ( 1.0.0 ) of https://github.com/magenizr/Magenizr_CustomShipping which is exactly the same code. I have removed the "_" from the shipping method name which supposed to fix the issue. Give it a shot with Magenizr_CustomShipping.

1. Remove the module `composer remove "tobias-forkel/magento2-customshipping" --no-update`
2. You may have to delete the record from table `setup_module` as well.
3. Install https://github.com/magenizr/Magenizr_CustomShipping

If you have any questions, feel free to open a new issue there.
